# Generated by Django 2.0.3 on 2018-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0002_auto_20180325_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rio',
            field=models.CharField(default='', max_length=20),
        ),
    ]
