# Generated by Django 2.0.3 on 2018-03-26 05:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginReg', '0003_auto_20180325_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userprofile',
            new_name='User',
        ),
    ]
