# Generated by Django 2.0.1 on 2018-03-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=10)),
                ('org', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(verbose_name='date registered')),
            ],
        ),
    ]
