# Generated by Django 2.0.3 on 2018-03-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0004_auto_20180326_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
